import {
  MASK_DISPLAY_OPACITY,
  MASK_SELECTED_DISPLAY_OPACITY,
  SELECTED_SHAPE_OPACITY,
  SHAPE_OPACITY
} from '../../../../shared/annotations'

export const DEFAULT_BRUSH_DIAMETER_IMAGE_PX = 40
export const MIN_BRUSH_DIAMETER_IMAGE_PX = 4
export const MAX_BRUSH_DIAMETER_IMAGE_PX = 200

export { MASK_DISPLAY_OPACITY, MASK_SELECTED_DISPLAY_OPACITY, SELECTED_SHAPE_OPACITY, SHAPE_OPACITY }

// CVAT masksHandler: drawingOpacity = 0.5
export const ACTIVE_STROKE_OPACITY = 0.5
export const SESSION_MASK_OPACITY = 0.5
export const COMMITTED_MASK_OPACITY = MASK_DISPLAY_OPACITY
export const COMMITTED_MASK_SELECTED_OPACITY = MASK_SELECTED_DISPLAY_OPACITY

// White brush ring preview (4px: outer 2px @ 100%, inner 2px @ 50% of base opacity)
export const BRUSH_PREVIEW_OPACITY = 1
export const BRUSH_PREVIEW_STROKE_IMAGE_PX = 4
export const BRUSH_PREVIEW_INNER_STROKE_IMAGE_PX = 2
export const BRUSH_PREVIEW_PRESSED_OPACITY_FACTOR = 0.5
