import { SELECTED_SHAPE_OPACITY, SHAPE_OPACITY } from '../../../../shared/annotations'

export const DEFAULT_BRUSH_DIAMETER_IMAGE_PX = 40
export const MIN_BRUSH_DIAMETER_IMAGE_PX = 4
export const MAX_BRUSH_DIAMETER_IMAGE_PX = 200

export { SELECTED_SHAPE_OPACITY, SHAPE_OPACITY }

export const SESSION_MASK_OPACITY = 0.6
export const ACTIVE_STROKE_OPACITY = 0.6
export const COMMITTED_MASK_OPACITY = 0.4

export const BRUSH_PREVIEW_STROKE_IMAGE_PX = 4
export const BRUSH_PREVIEW_INNER_STROKE_IMAGE_PX = 2
export const BRUSH_PREVIEW_OUTER_OPACITY = 0.8
export const BRUSH_PREVIEW_INNER_OPACITY = 0.4
